name: "Demo github workflow"
on: 
  push:
    branches:
      - '!main' # don't run workflow for main branch
      - 'dev' 
    # paths-ignore:
    #   - '.github/**' #ignore the workflow if the push is on path .github/ 
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: log message
              run: echo "Hello"     
            - name: main branch changes
              run: echo "main branch change"
        
