name: "Demo github workflow"
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: log message
              run: echo "Hello"
            - name: main branch changes
              run: echo "main branch change"
        
