name: Deployment of Python Application
on:
    push:
        branches:
            - 'dev'
        # paths:
        #     - 'python/ecommerce_api/**'
jobs:
    reusable-workflow:
        uses: ./.github/workflows/reusable_workflow.yml
