name: Deployment of Python Application
on:
    push:
        branches:
            - 'dev'
        # paths:
        #     - 'python/ecommerce_api/**'
jobs:
    reusable-workflow:
        uses: aditya3340/devops-essentials/.github/workflows/reusable_workflow.yaml@dev
